In [1]:
# menghubungkan drive ke collab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd "/content/drive/MyDrive/Statistika"

/content/drive/MyDrive/Statistika

In [2]:
import pandas as pd
path = '/content/drive/MyDrive/Statistika/MovieData-2018-2020.csv'
data = pd.read_csv(path)

In [ ]:
data["genre"].value_counts()

genre
Action       88
Comedy       45
Drama        38
Biography    29
Animation    23
Adventure    19
Horror       15
Crime        12
Fantasy       3
Thriller      1
Sci-Fi        1
Name: count, dtype: int64

In [ ]:
filtered_data = data.groupby('genre').filter(lambda x: len(x) > 1)
filtered_data["genre"].value_counts()

genre
Action       88
Comedy       45
Drama        38
Biography    29
Animation    23
Adventure    19
Horror       15
Crime        12
Fantasy       3
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
_, stratified_sample = train_test_split(
    filtered_data,
    test_size=0.2,               # Ambil 20% data dari setiap kelas
    stratify=filtered_data['genre'],      # Stratifikasi berdasarkan kolom 'genre'
    random_state=38
)
# Hasil stratified_sample berisi 20% sampel dari setiap genre
stratified_sample

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
139,Dragon Ball Super: Broly,PG,Animation,2018,"January 16, 2019 (United States)",7.8,24000.0,Tatsuya Nagamine,Akira Toriyama,Masako Nozawa,Japan,8500000.0,1.157579e+08,Toei Company,100.0
96,Overboard,PG-13,Comedy,2018,"May 4, 2018 (United States)",6.0,36000.0,Rob Greenberg,Bob Fisher,Eugenio Derbez,United States,12000000.0,9.124491e+07,Metro-Goldwyn-Mayer (MGM),112.0
222,Dumbo,PG,Adventure,2019,"March 29, 2019 (United States)",6.3,69000.0,Tim Burton,Ehren Kruger,Colin Farrell,United States,170000000.0,3.532846e+08,Walt Disney Pictures,112.0
226,The Kitchen,R,Action,2019,"August 9, 2019 (United States)",5.5,18000.0,Andrea Berloff,Andrea Berloff,Melissa McCarthy,United States,38000000.0,1.598003e+07,BRON Studios,102.0
4,Black Panther,PG-13,Action,2018,"February 16, 2018 (United States)",7.3,661000.0,Ryan Coogler,Ryan Coogler,Chadwick Boseman,United States,200000000.0,1.347598e+09,Marvel Studios,134.0
248,Poms,PG-13,Comedy,2019,"May 10, 2019 (United States)",6.0,4700.0,Zara Hayes,Zara Hayes,Diane Keaton,United Kingdom,10000000.0,1.641822e+07,Entertainment One,90.0
77,Widows,R,Crime,2018,"November 16, 2018 (United States)",6.9,91000.0,Steve McQueen,Gillian Flynn,Viola Davis,United Kingdom,42000000.0,7.598470e+07,New Regency Productions,129.0
98,A Wrinkle in Time,PG,Adventure,2018,"March 9, 2018 (United States)",4.2,42000.0,Ava DuVernay,Jennifer Lee,Storm Reid,United States,100000000.0,1.326759e+08,Legend3D,109.0
125,Second Act,PG-13,Comedy,2018,"December 21, 2018 (United States)",5.8,24000.0,Peter Segal,Justin Zackham,Jennifer Lopez,United States,16000000.0,7.229407e+07,Huayi Brothers,103.0
81,The Strangers: Prey at Night,R,Horror,2018,"March 9, 2018 (United States)",5.2,28000.0,Johannes Roberts,Bryan Bertino,Christina Hendricks,United States,5000000.0,3.103913e+07,Aviron Pictures,85.0
147,Little Women,PG,Drama,2019,"December 25, 2019 (United States)",7.8,159000.0,Greta Gerwig,Greta Gerwig,Saoirse Ronan,United States,40000000.0,2.166012e+08,Columbia Pictures,135.0
13,Crazy Rich Asians,PG-13,Comedy,2018,"August 15, 2018 (United States)",6.9,152000.0,Jon M. Chu,Peter Chiarelli,Constance Wu,United States,30000000.0,2.385392e+08,Warner Bros.,120.0
175,Glass,PG-13,Drama,2019,"January 18, 2019 (United States)",6.6,219000.0,M. Night Shyamalan,M. Night Shyamalan,James McAvoy,United States,20000000.0,2.469990e+08,Buena Vista International,129.0
169,Hellboy,R,Action,2019,"April 12, 2019 (United States)",5.2,82000.0,Neil Marshall,Andrew Cosby,David Harbour,United States,50000000.0,5.506529e+07,Summit Entertainment,120.0
51,Robin Hood,PG-13,Action,2018,"November 21, 2018 (United States)",5.3,68000.0,Otto Bathurst,Ben Chandler,Taron Egerton,United States,100000000.0,8.649305e+07,Summit Entertainment,116.0
272,Saving Mbango,NaN,Drama,2020,"April 27, 2020 (Cameroon)",5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,NaN,Embi Productions,NaN
112,Skyscraper,PG-13,Action,2018,"July 13, 2018 (United States)",5.8,111000.0,Rawson Marshall Thurber,Rawson Marshall Thurber,Dwayne Johnson,United States,125000000.0,3.048690e+08,Legendary Entertainment,102.0
146,Fighting with My Family,PG-13,Biography,2019,"February 22, 2019 (United States)",7.1,71000.0,Stephen Merchant,Stephen Merchant,Dwayne Johnson,United Kingdom,11000000.0,4.081192e+07,Metro-Goldwyn-Mayer (MGM),108.0
142,Nobody's Fool,R,Comedy,2018,"November 2, 2018 (United States)",4.9,7000.0,Tyler Perry,Tyler Perry,Tiffany Haddish,United States,19000000.0,3.370533e+07,BET Films,110.0
0,A Quiet Place,PG-13,Drama,2018,"April 6, 2018 (United States)",7.5,456000.0,John Krasinski,Bryan Woods,Emily Blunt,United States,17000000.0,3.503204e+08,Paramount Pictures,90.0
107,Insidious: The Last Key,PG-13,Horror,2018,"January 5, 2018 (United States)",5.7,55000.0,Adam Robitel,Leigh Whannell,Lin Shaye,United States,10000000.0,1.678856e+08,Blumhouse Productions,103.0
189,Frozen II,PG,Animation,2019,"November 22, 2019 (United States)",6.8,148000.0,Chris Buck,Jennifer Lee,Kristen Bell,United States,150000000.0,1.450027e+09,Walt Disney Animation Studios,103.0
270,The Robinsons,NaN,Action,2020,"November 10, 2020 (United States)",NaN,NaN,Directors,Aleks Alifirenko Jr.,Billy Hartmann,United States,10000.0,NaN,NaN,90.0
12,Green Book,PG-13,Biography,2018,"November 16, 2018 (United States)",8.2,414000.0,Peter Farrelly,Nick Vallelonga,Viggo Mortensen,United States,23000000.0,3.217527e+08,Participant,130.0
135,Stan & Ollie,PG,Biography,2018,"January 11, 2019 (United Kingdom)",7.2,34000.0,Jon S. Baird,Jeff Pope,Steve Coogan,United Kingdom,10000000.0,2.442092e+07,Entertainment One,98.0
140,Kin,PG-13,Action,2018,"August 31, 2018 (United States)",5.8,16000.0,Jonathan Baker,Jonathan Baker,Myles Truitt,United States,30000000.0,1.031302e+07,Summit Entertainment,102.0
64,Upgrade,R,Action,2018,"June 1, 2018 (United States)",7.5,168000.0,Leigh Whannell,Leigh Whannell,Logan Marshall-Green,United States,5000000.0,1.670668e+07,Goalpost Pictures,100.0
8,Ready Player One,PG-13,Action,2018,"March 29, 2018 (United States)",7.4,388000.0,Steven Spielberg,Zak Penn,Tye Sheridan,United States,175000000.0,5.828937e+08,Warner Bros.,140.0
240,Wonder Park,PG,Animation,2019,"March 15, 2019 (United States)",5.9,11000.0,Dylan Brown,Josh Appelbaum,Sofia Mali,Spain,90000000.0,1.195591e+08,Paramount Animation,85.0
174,Dora and the Lost City of Gold,PG,Adventure,2019,"August 9, 2019 (United States)",6.1,27000.0,James Bobin,Nicholas Stoller,Isabela Merced,United States,49000000.0,1.196826e+08,Paramount Players,102.0
133,Super Troopers 2,R,Comedy,2018,"April 20, 2018 (United States)",6.1,25000.0,Jay Chandrasekhar,Jay Chandrasekhar,Jay Chandrasekhar,United States,13500000.0,3.162639e+07,Votiv Films,99.0
176,The Best of Enemies,PG-13,Biography,2019,"April 5, 2019 (United States)",7.2,13000.0,Robin Bissell,Robin Bissell,Taraji P. Henson,United States,10000000.0,1.020981e+07,Astute Films,133.0
70,Mortal Engines,PG-13,Action,2018,"December 14, 2018 (United States)",6.1,115000.0,Christian Rivers,Fran Walsh,Hera Hilmar,United States,100000000.0,8.386982e+07,Media Rights Capital (MRC),128.0
42,The Equalizer 2,R,Action,2018,"July 20, 2018 (United States)",6.7,141000.0,Antoine Fuqua,Richard Wenk,Denzel Washington,United States,62000000.0,1.904002e+08,Columbia Pictures,121.0
15,BlacKkKlansman,R,Biography,2018,"August 10, 2018 (United States)",7.5,236000.0,Spike Lee,Charlie Wachtel,John David Washington,United States,15000000.0,9.341371e+07,Focus Features,135.0
190,Brightburn,R,Drama,2019,"May 24, 2019 (United States)",6.1,87000.0,David Yarovesky,Brian Gunn,Elizabeth Banks,United States,6000000.0,3.289342e+07,Screen Gems,90.0
48,Fantastic Beasts: The Crimes of Grindelwald,PG-13,Adventure,2018,"November 16, 2018 (United States)",6.5,234000.0,David Yates,J.K. Rowling,Eddie Redmayne,United Kingdom,200000000.0,6.548559e+08,Heyday Films,134.0
220,The Lego Movie 2: The Second Part,PG,Animation,2019,"February 8, 2019 (United States)",6.6,58000.0,Mike Mitchell,Phil Lord,Chris Pratt,Denmark,99000000.0,1.923065e+08,Warner Bros.,107.0
29,Eighth Grade,R,Comedy,2018,"August 3, 2018 (United States)",7.4,68000.0,Bo Burnham,Bo Burnham,Elsie Fisher,United States,2000000.0,1.434743e+07,A24,93.0
143,Midsommar,R,Drama,2019,"July 3, 2019 (United States)",7.1,232000.0,Ari Aster,Ari Aster,Florence Pugh,United States,9000000.0,4.796764e+07,A24,148.0
131,The 15:17 to Paris,PG-13,Biography,2018,"February 9, 2018 (United States)",5.3,30000.0,Clint Eastwood,Dorothy Blyskal,Alek Skarlatos,United States,30000000.0,5.707629e+07,Warner Bros.,94.0
56,Mary Poppins Returns,PG,Comedy,2018,"December 19, 2018 (United States)",6.7,80000.0,Rob Marshall,P.L. Travers,Emily Blunt,United States,130000000.0,3.495461e+08,Lucamar Productions,130.0
157,Spider-Man: Far from Home,PG-13,Action,2019,"July 2, 2019 (United States)",7.5,359000.0,Jon Watts,Chris McKenna,Tom Holland,United States,160000000.0,1.131928e+09,Columbia Pictures,129.0
260,Birds of Prey,R,Action,2020,"February 7, 2020 (United States)",6.1,190000.0,Cathy Yan,Christina Hodson,Margot Robbie,United States,84500000.0,2.018585e+08,Clubhouse Pictures (II),109.0
94,Truth or Dare,PG-13,Horror,2018,"April 13, 2018 (United States)",5.2,50000.0,Jeff Wadlow,Michael Reisz,Lucy Hale,United States,3500000.0,9.533071e+07,Blumhouse Productions,100.0
238,Miss Bala,PG-13,Action,2019,"February 1, 2019 (United States)",5.8,9900.0,Catherine Hardwicke,Gareth Dunnet-Alcocer,Gina Rodriguez,Mexico,15000000.0,1.538358e+07,Canana Films,104.0
128,If Beale Street Could Talk,R,Drama,2018,"December 25, 2018 (United States)",7.1,45000.0,Barry Jenkins,Barry Jenkins,KiKi Layne,United States,12000000.0,2.059657e+07,Annapurna Pictures,119.0
218,Weathering with You,PG-13,Animation,2019,"January 17, 2020 (United States)",7.5,28000.0,Makoto Shinkai,Makoto Shinkai,Kotaro Daigo,Japan,11100000.0,1.934575e+08,"""Weathering With You"" Film Partners",112.0
205,Pokémon Detective Pikachu,PG,Action,2019,"May 10, 2019 (United States)",6.6,146000.0,Rob Letterman,Dan Hernandez,Ryan Reynolds,United States,150000000.0,4.339213e+08,Warner Bros.,104.0
28,Jurassic World: Fallen Kingdom,PG-13,Action,2018,"June 22, 2018 (United States)",6.2,277000.0,J.A. Bayona,Derek Connolly,Chris Pratt,United States,170000000.0,1.310466e+09,Universal Pictures,128.0
186,Angel Has Fallen,R,Action,2019,"August 23, 2019 (United States)",6.4,86000.0,Ric Roman Waugh,Robert Mark Kamen,Gerard Butler,United States,40000000.0,1.466620e+08,Millennium Media,121.0
46,The Hate U Give,PG-13,Crime,2018,"October 19, 2018 (United States)",7.5,33000.0,George Tillman Jr.,Audrey Wells,Amandla Stenberg,United States,23000000.0,3.493401e+07,Fox 2000 Pictures,133.0
55,"Love, Simon",PG-13,Comedy,2018,"March 16, 2018 (United States)",7.6,104000.0,Greg Berlanti,Becky Albertalli,Nick Robinson,United States,17000000.0,6.631629e+07,Fox 2000 Pictures,110.0
73,Creed II,PG-13,Drama,2018,"November 21, 2018 (United States)",7.1,111000.0,Steven Caple Jr.,Juel Taylor,Michael B. Jordan,United States,50000000.0,2.142159e+08,Metro-Goldwyn-Mayer (MGM),130.0
227,Stuber,R,Action,2019,"July 12, 2019 (United States)",6.2,43000.0,Michael Dowse,Tripper Clancy,Dave Bautista,United States,16000000.0,3.239094e+07,GoldDay,93.0

In [ ]:
stratified_sample.describe()

,year,score,votes,budget,gross,runtime
count,55.000000,54.000000,54.000000,5.500000e+01,5.300000e+01,54.000000
mean,2018.472727,6.490741,118233.870370,5.425761e+07,2.319792e+08,112.277778
std,0.604138,0.875294,132733.148615,5.927952e+07,3.434769e+08,16.115639
min,2018.000000,4.200000,29.000000,1.000000e+04,1.020981e+07,85.000000
25%,2018.000000,5.825000,28500.000000,1.105000e+07,3.370533e+07,100.500000
50%,2018.000000,6.550000,70000.000000,2.300000e+07,9.533071e+07,109.500000
75%,2019.000000,7.200000,151000.000000,9.450000e+07,2.385392e+08,128.750000
max,2020.000000,8.200000,661000.000000,2.000000e+08,1.450027e+09,148.000000

In [ ]:
import pandas as pd
import scipy.stats as stats
import math

x_bar = 5.425761e+07
s = 5.927952e+07
n = 30
confidence_level = 0.95

alpha = (1 - confidence_level)
df = n - 1
standard_error = s / math.sqrt(n)
critical_t = stats.t.ppf(1 - alpha/2, df)
margin_of_error = critical_t * standard_error

lower_bound = x_bar - margin_of_error
upper_bound = x_bar + margin_of_error

print("=== RINGKASAN DATA ===")
print("Jumlah Sampel Film (n)   : {}".format(n))
print("Rata-rata Budget (x_bar) : ${:,.2f}".format(x_bar))
print("Standar Deviasi (s)      : ${:,.2f}".format(s))
print("Critical t-value         : {:.3f}".format(critical_t))
print("Margin of Error          : ${:,.2f}".format(margin_of_error))
print("-" * 50)
print("{:.1%} Interval kepercayaan untuk rata-rata populasi adalah:".format(confidence_level))
print("diantara ${:,.2f} and ${:,.2f}".format(lower_bound, upper_bound))

=== RINGKASAN DATA ===
Jumlah Sampel Film (n)   : 30
Rata-rata Budget (x_bar) : $54,257,610.00
Standar Deviasi (s)      : $59,279,520.00
Critical t-value         : 2.045
Margin of Error          : $22,135,336.55
--------------------------------------------------
95.0% Interval kepercayaan untuk rata-rata populasi adalah:
diantara $32,122,273.45 and $76,392,946.55